### ISSUE TITLE
Error "Verify Cypress" on v5.0.0

### ISSUE THREAD

**Issue by avallete** [cypress-io/circleci-orb#308]
## The orb does not work as expected

- what version of the orb are you currently using?
  - v1.26.0
- paste the `circle.yml` file if possible or at least the relevant portion
```version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
jobs:
  release:
    executor: cypress/base-14
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run semantic-release
workflows:
  build:
    jobs:
      - cypress/run:
          executor: cypress/browsers-chrome69
          browser: chrome
      - release:
          requires:
            - cypress/run
```
- describe what you think should happen

Setup Cypress, then run the tests.

- describe what happens

I have an error on the "Verify Cypress" stage, telling me that there is a librarie missing for cypress to run:

![image](https://user-images.githubusercontent.com/8771783/91247403-90944180-e795-11ea-9001-144bb8d87693.png)

**Comment by jennifer-shehane** [comment]
The required deps have been updated for 5.0, since we upgraded Electron. All deps are here: https://docs.cypress.io/guides/getting-started/installing-cypress.html#Linux

If there's an issue with a specific docker images deps, I'd suggest opening the issue in https://github.com/cypress-io/cypress-docker-images
