### ISSUE TITLE
Use the circleci/node images as base

### ISSUE THREAD

**Issue by chmanie** [cypress-io/circleci-orb#46]
For our test setup we rely on docker commands, so we need to run those in circleci (using the `setup_remote_docker` step, see [here](https://circleci.com/docs/2.0/building-docker-images/)). Sadly this option is only available when basing on the official circleci node images `circleci/node:xx`. The cypress images though are based on the `node:xx` images which do not support this.
There might be even more capabilities the official circleci images are adding that won't be supported when using `node:xx`.

I know this is kind of a stretch and that'd mean more images/dockerfiles to maintain for you but as this is a circleci specific orb, I thought I'd kindly ask. Currently we're working around this by rolling our own docker image: https://github.com/JoinColony/colony-docker-images/blob/master/circleci-cypress/Dockerfile, but I see that a lot of work went into this orb and I'd really like to use it :)

**Comment by bahmutov** [comment]
so I feel using Circle specific Docker images brings a lot of tools and weight that is not really needed. So we don't want to switch Cypress official images to that base. But what is needed here is probably a way to specify custom Docker image or machine as Orb job executor. I would be open to a pull request that implements it. That way people could do something like 

```
# import cypress orb
cypress/run:
  executor: circleci/node:10
```

Of course this is assuming that image `circleci/node:10` has all dependencies. Otherwise you would still need to make your own custom Docker image first

**Comment by bahmutov** [comment]
@chmanie I have documented how to use any executor to run the job https://github.com/cypress-io/circleci-orb/blob/master/docs/examples.md#custom-executor

But of course, these images need OS dependencies. Let me know if more information is needed
